language: en

pipeline:
- name: WhitespaceTokenizer
- name: CountVectorsFeaturizer
- name: DIETClassifier
- name: EntitySynonymMapper
- name: ResponseSelector
- name: FallbackClassifier

policies:
- name: RulePolicy
- name: MemoizationPolicy
- name: TEDPolicy
assistant_id: 20251016-151459-crazy-dialogue
